[versions]
compose = "1.2.0-beta02"
accompanist = "0.24.9-beta"

[libraries]
activity = "androidx.activity:activity-compose:1.6.0-alpha03"
foundation = { module = "androidx.compose.foundation:foundation", version.ref="compose" }
animation = { module = "androidx.compose.animation:animation", version.ref="compose" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref="compose" }

material3-core = "androidx.compose.material3:material3:1.0.0-alpha12"
material3-adapter = "com.google.android.material:compose-theme-adapter-3:1.0.9"
material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref="compose" }

accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref="accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref="accompanist" }